# Generated by Django 5.2.7 on 2025-10-28 10:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_remove_feedback_comments_course_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['department', 'name']},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['faculty', 'name']},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AlterModelOptions(
            name='lecturer',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
