# Generated by Django 5.2.7 on 2025-10-28 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_alter_course_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='student_name',
        ),
    ]
